#!/bin/bash
# Scott's brewfile

# Taps
tap 'caskroom/versions' # For Sublime Text 3

# Install Homebrew packages
brew 'caskroom/cask/brew-cask'
brew 'bash-completion'
brew 'git'
brew 'macvim'
brew 'python'
brew 'python3'
brew 'shellcheck' # Used by SublimeLinter-shellcheck

# Install Cask Apps
cask 'google-chrome'
cask 'sublime-text3'
cask 'slack'
cask 'spotify'
