#!/bin/bash
# Scott's brewfile

# Taps
tap 'caskroom/cask'

# Install Homebrew packages
brew 'bash-completion'
brew 'git'
brew 'node'
brew 'phantomjs'
brew 'python3'
brew 'shellcheck' # Used by SublimeLinter-shellcheck
brew 'wget'

# Install Cask Apps
cask 'google-chrome'
cask 'sublime-text'
cask 'iterm2'
cask 'slack'
cask 'spotify'
